services:
  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: valhalla
    ports:
      - "8002:8002"
    volumes:
      - ./valhalla_tiles:/custom_valhalla_tiles
    environment:
      - tile_extract_url=https://download.geofabrik.de/europe/germany/bremen-latest.osm.pbf
      - build_elevation=false
      - build_transit=false
      - force_rebuild=false